#!/usr/bin/env python3
"""
JFrog Artifactory Configuration and Testing

This script:
1. Tests JFrog connectivity if credentials are configured
2. Configures pip to use JFrog as PRIMARY index (with public PyPI as fallback)
3. Creates pip.conf with JFrog authentication

If JFrog credentials are configured but don't work, this script FAILS HARD.
"""

import os
import subprocess
import sys
import urllib.parse
from pathlib import Path


def test_jfrog_connectivity() -> bool:
    """Test JFrog Artifactory connectivity."""
    has_token = bool(os.environ.get("JF_TOKEN"))
    has_userpass = bool(os.environ.get("JF_USER") and os.environ.get("JF_PASSWORD"))

    if not (has_token or has_userpass):
        print("[INFO] No JFrog credentials - JFrog is optional")
        return True  # No credentials = no test

    print("[INFO] Testing JFrog connectivity...")

    # Build auth
    if has_token:
        auth_user = os.environ.get("JF_TOKEN_USER", "artifactory@hypersec.io")
        auth_pass = os.environ.get("JF_TOKEN")
    else:
        auth_user = os.environ.get("JF_USER")
        auth_pass = os.environ.get("JF_PASSWORD")

    # Test API ping
    try:
        result = subprocess.run(
            ["curl", "-f", "-s", "-u", f"{auth_user}:{auth_pass}",
             "https://hypersec.jfrog.io/artifactory/api/system/ping"],
            capture_output=True,
            text=True,
            timeout=10
        )

        if result.returncode == 0 and "OK" in result.stdout:
            print("[OK] JFrog accessible and working")
            return True
        else:
            print(f"[ERR] JFrog ping failed: {result.stdout[:100]}")
            return False

    except Exception as e:
        print(f"[ERR] JFrog connectivity test failed: {e}")
        return False


def configure_jfrog_pip() -> bool:
    """Configure pip to use JFrog as PRIMARY index."""
    has_token = bool(os.environ.get("JF_TOKEN"))
    has_userpass = bool(os.environ.get("JF_USER") and os.environ.get("JF_PASSWORD"))

    if not (has_token or has_userpass):
        print("[INFO] No JFrog credentials - skipping pip configuration")
        return True

    print("[INFO] Configuring pip to use JFrog as PRIMARY index...")

    # Build authenticated URL
    jf_host = os.environ.get("JF_PYPI_HOST", "hypersec.jfrog.io/artifactory/api/pypi/hypersec-pypi-local/simple")

    if has_token:
        jf_token_user = os.environ.get("JF_TOKEN_USER", "artifactory@hypersec.io")
        jf_token = os.environ.get("JF_TOKEN")
        user_encoded = urllib.parse.quote(jf_token_user, safe='')
        token_encoded = urllib.parse.quote(jf_token, safe='')
        pip_index_url = f"https://{user_encoded}:{token_encoded}@{jf_host}"
        print(f"[INFO] Using token auth (user: {jf_token_user})")
    else:
        jf_user = os.environ.get("JF_USER")
        jf_password = os.environ.get("JF_PASSWORD")
        user_encoded = urllib.parse.quote(jf_user, safe='')
        password_encoded = urllib.parse.quote(jf_password, safe='')
        pip_index_url = f"https://{user_encoded}:{password_encoded}@{jf_host}"
        print(f"[INFO] Using username/password auth (user: {jf_user})")

    # Set environment variables
    os.environ["PIP_INDEX_URL"] = pip_index_url
    os.environ["PIP_EXTRA_INDEX_URL"] = "https://pypi.org/simple"

    # Create pip.conf
    pip_conf_content = f"""# Auto-generated by bootstrap - DO NOT COMMIT
# JFrog is PRIMARY index, public PyPI is SECONDARY (fallback for dependencies)

[global]
index-url = {pip_index_url}
extra-index-url = https://pypi.org/simple

[install]
trusted-host = hypersec.jfrog.io
"""

    # Write to .pip/pip.conf
    pip_conf_dir = Path.cwd() / ".pip"
    pip_conf_dir.mkdir(exist_ok=True)
    pip_conf = pip_conf_dir / "pip.conf"
    pip_conf.write_text(pip_conf_content)

    # Also write to ci/.venv/pip.conf
    venv_pip_conf = Path.cwd() / "ci/.venv" / "pip.conf"
    if venv_pip_conf.parent.exists():
        venv_pip_conf.write_text(pip_conf_content)
        print(f"[OK] Created pip.conf in .pip/ and ci/.venv/")
    else:
        print(f"[OK] Created pip.conf in .pip/ (ci/.venv not yet created)")

    os.environ["PIP_CONFIG_FILE"] = str(pip_conf)
    return True


def main() -> int:
    """Main entry point."""
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} [check|install]", file=sys.stderr)
        return 1

    action = sys.argv[1]

    if action == "check":
        # Test connectivity and configure pip
        if not test_jfrog_connectivity():
            print("")
            print("[ERR] JFrog configured but NOT working!")
            print("[ERR] Fix credentials or remove them from .env")
            return 1

        configure_jfrog_pip()
        return 0

    elif action == "install":
        # Same as check - configure pip
        if not test_jfrog_connectivity():
            return 1
        configure_jfrog_pip()
        return 0

    else:
        print(f"[ERR] Unknown action: {action}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
