#!/usr/bin/env python3
"""
Configure JFrog Artifactory access for pip operations

This script automatically constructs PIP_EXTRA_INDEX_URL from environment variables,
handling URL encoding of credentials and supporting both token and username/password auth.

Environment Variables (set in .env):
  - JF_TOKEN: JFrog access token (preferred, if available)
  - JF_TOKEN_USER: Username for token auth (default: artifactory@hypersec.io)
  - JF_USER: JFrog username (fallback auth)
  - JF_PASSWORD: JFrog password (fallback auth)
  - JF_PYPI_HOST: JFrog PyPI repository host
"""

import os
import sys
import urllib.parse
from pathlib import Path

# Import from ci_lib (loguru with RFC 3339 timestamps)
sys.path.insert(0, str(Path(__file__).parent.parent))
from ci_lib import logger


def configure_jfrog_pip():
    """Set up pip to access JFrog Artifactory using credentials from environment"""

    # Get credentials from environment
    jf_token = os.getenv("JF_TOKEN")
    jf_user = os.getenv("JF_USER")
    jf_password = os.getenv("JF_PASSWORD")
    jf_host = os.getenv("JF_PYPI_HOST", "hypersec.jfrog.io/artifactory/api/pypi/hypersec-pypi-local/simple")

    # Determine authentication method
    if jf_token:
        # Token authentication (preferred)
        # URL-encode token to handle special characters
        token_encoded = urllib.parse.quote(jf_token, safe='')
        # Token auth requires specific username (artifactory@hypersec.io)
        jf_token_user = os.getenv("JF_TOKEN_USER", "artifactory@hypersec.io")
        user_encoded = urllib.parse.quote(jf_token_user, safe='')
        pip_extra_index = f"https://{user_encoded}:{token_encoded}@{jf_host}"
        logger.info(f"Using JFrog access token with user {jf_token_user} for pip authentication")

    elif jf_user and jf_password:
        # Username/password authentication (fallback)
        # URL-encode both username and password to handle special characters
        user_encoded = urllib.parse.quote(jf_user, safe='')
        password_encoded = urllib.parse.quote(jf_password, safe='')
        pip_extra_index = f"https://{user_encoded}:{password_encoded}@{jf_host}"
        logger.info(f"Using JFrog username/password for pip authentication (user: {jf_user})")

    else:
        logger.info("No JFrog credentials found - JFrog access is optional")
        logger.info("To enable JFrog, set one of:")
        logger.info("  - JF_TOKEN + JF_TOKEN_USER (preferred)")
        logger.info("  - JF_USER + JF_PASSWORD (fallback)")
        return True  # Success - JFrog is optional

    # Export for current process and all subprocesses (including nox, pip, etc.)
    os.environ["PIP_EXTRA_INDEX_URL"] = pip_extra_index
    logger.info("Set PIP_EXTRA_INDEX_URL environment variable")

    # Create pip configuration content
    pip_conf_content = f"""# Auto-generated by bootstrap - DO NOT COMMIT
# This file is created from environment variables in .env
# Credentials are automatically URL-encoded

[global]
extra-index-url = {pip_extra_index}

[install]
trusted-host = hypersec.jfrog.io
"""

    # Write to .pip/pip.conf for reference and PIP_CONFIG_FILE
    pip_conf_dir = Path.cwd() / ".pip"
    pip_conf_dir.mkdir(exist_ok=True)
    pip_conf = pip_conf_dir / "pip.conf"
    pip_conf.write_text(pip_conf_content)

    # ALSO write to ci/.venv/pip.conf (site-level config for the venv)
    # This is where pip actually looks for venv-specific configuration
    venv_ci_pip_conf = Path.cwd() / "ci/.venv" / "pip.conf"
    if venv_ci_pip_conf.parent.exists():
        venv_ci_pip_conf.write_text(pip_conf_content)
        logger.info(f"Created pip config: {pip_conf} and {venv_ci_pip_conf}")
    else:
        logger.info(f"Created pip config: {pip_conf} (ci/.venv not yet created)")

    # Set PIP_CONFIG_FILE so pip uses this config in current process
    os.environ["PIP_CONFIG_FILE"] = str(pip_conf)

    return True


if __name__ == "__main__":
    success = configure_jfrog_pip()
    sys.exit(0 if success else 1)
