# Project:   hyperi-pylib
# File:      deployment/app_project.py
# Purpose:   Generate ArgoCD AppProject CRs
# Language:  Python
#
# License:   FSL-1.1-ALv2
# Copyright: (c) 2026 HYPERI PTY LIMITED
"""ArgoCD ``AppProject`` generator.

:class:`AppProjectContract` describes a per-team or per-business-unit
ArgoCD project with restricted ``sourceRepos``, ``destinations``, and
``roles``. Consumer Applications reference the project via their
``spec.project`` field.

Mirrors ``hyperi_rustlib::deployment::app_project`` for byte-level
cross-language parity.

See the spec section 3.5 in
``docs/superpowers/specs/2026-05-15-argocd-enterprise-enhancements-spec.md``.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class AppProjectDestination:
    """Cluster + namespace pair an AppProject may target.

    Attributes:
        server: Cluster server URL (e.g. ``https://kubernetes.default.svc``).
        namespace: Namespace the project may deploy into. Use ``"*"`` to allow any.
    """

    server: str
    namespace: str


@dataclass
class AppProjectContract:
    """``AppProject`` declaration.

    Becomes one ``argoproj.io/v1alpha1 AppProject`` CR scoped to a team.

    Attributes:
        name: Project name. Used as ``metadata.name``. Lowercase, RFC-1123-ish.
        argocd_namespace: ArgoCD namespace (where the CR lives). Usually ``argocd``.
        description: Human-readable description. Becomes ``spec.description``.
        source_repos: Source repositories permitted for Applications in this
            project. Use ``["*"]`` for unrestricted (not recommended for enterprise).
        destinations: Cluster/namespace pairs permitted for Applications in this project.
        cluster_resource_allow: Cluster-scoped resource kinds that Applications
            may create. Format: ``["<group>:<kind>"]`` e.g.
            ``["kafka.strimzi.io:KafkaTopic"]``. Use ``["*:*"]`` for unrestricted.
        namespace_resource_allow: Namespaced resource kinds that Applications
            may create. Same format as ``cluster_resource_allow``.
    """

    name: str = ""
    argocd_namespace: str = "argocd"
    description: str = ""
    source_repos: list[str] = field(default_factory=lambda: ["*"])
    destinations: list[AppProjectDestination] = field(
        default_factory=lambda: [
            AppProjectDestination(
                server="https://kubernetes.default.svc",
                namespace="*",
            )
        ]
    )
    cluster_resource_allow: list[str] = field(default_factory=lambda: ["*:*"])
    namespace_resource_allow: list[str] = field(default_factory=lambda: ["*:*"])


def generate_argocd_app_project(project: AppProjectContract) -> str:
    """Generate an ``AppProject`` YAML manifest from a contract.

    Args:
        project: The AppProject contract describing scope + permissions.

    Returns:
        ``AppProject`` YAML as a UTF-8 string with LF line endings.
    """
    lines: list[str] = [
        "# AUTOGENERATED -- do not edit by hand.",
        "# Generated by hyperi_pylib.deployment.generate_argocd_app_project()",
        "apiVersion: argoproj.io/v1alpha1",
        "kind: AppProject",
        "metadata:",
        f"  name: {project.name}",
        f"  namespace: {project.argocd_namespace}",
        "spec:",
        f"  description: {_quote_if_needed(project.description)}",
        "  sourceRepos:",
    ]
    for repo in project.source_repos:
        lines.append(f"    - {repo}")
    lines.append("  destinations:")
    for dest in project.destinations:
        lines.append(f"    - server: {dest.server}")
        lines.append(f"      namespace: {dest.namespace}")
    lines.append("  clusterResourceWhitelist:")
    for entry in project.cluster_resource_allow:
        group, kind = _split_resource(entry)
        lines.append(f"    - group: {group}")
        lines.append(f"      kind: {kind}")
    lines.append("  namespaceResourceWhitelist:")
    for entry in project.namespace_resource_allow:
        group, kind = _split_resource(entry)
        lines.append(f"    - group: {group}")
        lines.append(f"      kind: {kind}")
    return "\n".join(lines) + "\n"


def _split_resource(entry: str) -> tuple[str, str]:
    """Split a ``<group>:<kind>`` resource string into ``(group, kind)``."""
    if ":" in entry:
        group, _, kind = entry.partition(":")
        return group, kind
    return "*", "*"


def _quote_if_needed(s: str) -> str:
    """Quote a YAML scalar if it contains special characters or is empty."""
    if ":" in s or "#" in s or not s:
        return f'"{s}"'
    return s


__all__ = [
    "AppProjectContract",
    "AppProjectDestination",
    "generate_argocd_app_project",
]
