{{- if .Values.keda.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "hs-lib-app.fullname" . }}
  labels:
    {{- include "hs-lib-app.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    name: {{ include "hs-lib-app.fullname" . }}
  minReplicaCount: {{ .Values.keda.minReplicaCount }}
  maxReplicaCount: {{ .Values.keda.maxReplicaCount }}
  pollingInterval: {{ .Values.keda.pollingInterval }}
  cooldownPeriod: {{ .Values.keda.cooldownPeriod }}
  triggers:
    {{- toYaml .Values.keda.triggers | nindent 4 }}
{{- end }}
