#!/usr/bin/env python3
import sys
from pathlib import Path

CI_DIR = Path(__file__).resolve().parent
PYTHON_DIR = CI_DIR / "python"
sys.path.insert(0, str(PYTHON_DIR))
from bootstrap import main  # type: ignore


if __name__ == "__main__":
    raise SystemExit(main())

