#!/usr/bin/env python3
import sys
from pathlib import Path

THIS_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(THIS_DIR))
from bootstrap import main  # type: ignore


if __name__ == "__main__":
    raise SystemExit(main())

