apiVersion: v2
name: hyperi-pylib-app
description: HELM chart for hyperi-pylib applications (API, Daemon, MCP)
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - hyperi-pylib
  - python
  - api
  - daemon
  - kubernetes
maintainers:
  - name: HyperI
    url: https://github.com/hyperi-io/hyperi-pylib
