#!/usr/bin/env python3
import json
import logging
import os
import re
import subprocess
import sys
from datetime import datetime
from pathlib import Path


def _is_tty() -> bool:
    try:
        return sys.stdout.isatty() and not os.environ.get("NO_COLOR")
    except Exception:
        return False


class SolarizedFormatter(logging.Formatter):
    COLORS = {
        "DEBUG": "\033[38;5;33m",
        "INFO": "\033[38;5;64m",
        "OK": "\033[38;5;64m",
        "WARNING": "\033[38;5;136m",
        "ERROR": "\033[38;5;160m",
        "CRITICAL": "\033[38;5;160m",
    }
    CYAN = "\033[36m"
    TIME = "\033[38;5;64m"
    RESET = "\033[0m"

    def formatTime(self, record, datefmt=None):
        dt = datetime.now().astimezone()
        if "%f" in (datefmt or ""):
            return dt.strftime(datefmt)
        return dt.strftime("%Y-%m-%dT%H:%M:%S.%f%z")[:-3]

    def format(self, record: logging.LogRecord) -> str:
        t = self.formatTime(record)
        level = record.levelname
        name = record.name
        func = record.funcName
        line = record.lineno
        msg = record.getMessage()
        if _is_tty():
            lvl_color = self.COLORS.get(level, self.CYAN)
            return (
                f"{self.TIME}{t}{self.RESET} | "
                f"{lvl_color}{level:<8}{self.RESET} | "
                f"{self.CYAN}{name}{self.RESET}:{self.CYAN}{func}{self.RESET}:{self.CYAN}{line}{self.RESET} - "
                f"{lvl_color}{msg}{self.RESET}"
            )
        return f"{t} | {level:<8} | {name}:{func}:{line} - {msg}"


def setup_logger() -> logging.Logger:
    logger = logging.getLogger("clean-commit")
    logger.setLevel(logging.INFO)
    logger.handlers.clear()

    sh = logging.StreamHandler(sys.stdout)
    sh.setFormatter(SolarizedFormatter())
    logger.addHandler(sh)

    log_file = os.environ.get("CI_LOG_FILE")
    if log_file:
        os.makedirs(os.path.dirname(log_file), exist_ok=True)
        if os.environ.get("CI_LOG_STRUCTURED") == "1":
            class JSONFormatter(logging.Formatter):
                def format(self, record: logging.LogRecord) -> str:
                    dt = datetime.now().astimezone()
                    t = dt.strftime("%Y-%m-%dT%H:%M:%S.%f%z")[:-3]
                    payload = {
                        "time": t,
                        "level": record.levelname,
                        "name": record.name,
                        "function": record.funcName,
                        "line": record.lineno,
                        "message": record.getMessage(),
                    }
                    return json.dumps(payload, ensure_ascii=True)
            fh = logging.FileHandler(log_file)
            fh.setFormatter(JSONFormatter())
            logger.addHandler(fh)
        else:
            fh = logging.FileHandler(log_file)
            fh.setFormatter(logging.Formatter("%(asctime)s | %(levelname)-8s | %(name)s:%(funcName)s:%(lineno)d - %(message)s",
                                             datefmt="%Y-%m-%dT%H:%M:%S.%f%z"))
            logger.addHandler(fh)
    return logger


log = setup_logger()


def get_last_commit_message() -> str:
    """Get the last commit message."""
    try:
        out = subprocess.check_output(
            ["git", "log", "-1", "--format=%B"],
            stderr=subprocess.STDOUT
        )
        return out.decode("utf-8").strip()
    except subprocess.CalledProcessError as exc:
        log.error(f"Failed to get last commit message: {exc}")
        sys.exit(1)


def get_git_user() -> tuple[str, str]:
    """Get current git user name and email."""
    try:
        name = subprocess.check_output(
            ["git", "config", "user.name"],
            stderr=subprocess.STDOUT
        ).decode("utf-8").strip()

        email = subprocess.check_output(
            ["git", "config", "user.email"],
            stderr=subprocess.STDOUT
        ).decode("utf-8").strip()

        return name, email
    except subprocess.CalledProcessError as exc:
        log.error(f"Failed to get git user: {exc}")
        sys.exit(1)


def clean_commit_message(message: str) -> str:
    """
    Remove AI assistant attribution lines from commit message.

    Removes attribution from:
    -
    - GitHub Copilot
    - Cursor
    - Codex
    - Other AI assistants

    Patterns removed:
    - "🤖 Generated with [AI Name](...)"
    - "Co-Authored-By: [AI Name] <email>"
    - Lines containing "Generated by", "Created with", "Assisted by"
    - Empty lines at the end
    """
    lines = message.split("\n")
    cleaned_lines = []

    # Patterns to match AI attribution
    ai_patterns = [
        #
        r".*Generated with.*.*",
        r".*Co-Authored-By:\s*\s*<.*>.*",
        # GitHub Copilot
        r".*Generated by.*Copilot.*",
        r".*Co-Authored-By:\s*GitHub Copilot.*",
        r".*Assisted by.*Copilot.*",
        # Cursor
        r".*Generated with.*Cursor.*",
        r".*Co-Authored-By:\s*Cursor.*",
        r".*Created with.*Cursor.*",
        # Codex
        r".*Generated by.*Codex.*",
        r".*Co-Authored-By:\s*Codex.*",
        # Generic AI patterns
        r".*Generated by AI.*",
        r".*AI-generated.*",
        r".*Co-Authored-By:\s*AI\s*<.*>.*",
        # Emoji robot lines
        r"^\s*🤖.*",
    ]

    compiled_patterns = [re.compile(p, re.IGNORECASE) for p in ai_patterns]

    for line in lines:
        # Check if line matches any AI attribution pattern
        if any(pattern.match(line) for pattern in compiled_patterns):
            continue
        cleaned_lines.append(line)

    # Remove trailing empty lines
    while cleaned_lines and not cleaned_lines[-1].strip():
        cleaned_lines.pop()

    return "\n".join(cleaned_lines)


def amend_commit(cleaned_message: str, author: str) -> None:
    """Amend the last commit with cleaned message and current user as author."""
    try:
        # Write cleaned message to temp file
        tmp_file = Path(".tmp/commit-msg-clean.txt")
        tmp_file.parent.mkdir(exist_ok=True)
        tmp_file.write_text(cleaned_message)

        # Amend commit with cleaned message and update author
        subprocess.run(
            [
                "git", "commit", "--amend",
                "-F", str(tmp_file),
                "--author", author,
                "--no-verify"  # Skip hooks to prevent recursion
            ],
            check=True,
            capture_output=True
        )

        tmp_file.unlink()
        log.info("Successfully amended commit with cleaned message")

    except subprocess.CalledProcessError as exc:
        log.error(f"Failed to amend commit: {exc}")
        log.error(f"stderr: {exc.stderr.decode('utf-8')}")
        sys.exit(1)


def check_commit_authorship() -> bool:
    """Check if the last commit was authored by the current user."""
    try:
        author = subprocess.check_output(
            ["git", "log", "-1", "--format=%an %ae"],
            stderr=subprocess.STDOUT
        ).decode("utf-8").strip()

        name, email = get_git_user()
        current_user = f"{name} {email}"

        if author != current_user:
            log.warning(f"Last commit author ({author}) differs from current user ({current_user})")
            log.warning("This script will update the author to current user")

        return True
    except subprocess.CalledProcessError as exc:
        log.error(f"Failed to check authorship: {exc}")
        return False


def main() -> int:
    """Main entry point."""
    # Check if we're in a git repo
    try:
        subprocess.run(
            ["git", "rev-parse", "--git-dir"],
            check=True,
            capture_output=True
        )
    except subprocess.CalledProcessError:
        log.error("Not in a git repository")
        return 1

    # Get last commit message
    message = get_last_commit_message()

    # Check if message contains any AI attribution
    ai_indicators = [
        "", "",
        "Copilot", "Cursor", "Codex",
        "Generated by", "Generated with",
        "AI-generated", "🤖"
    ]

    has_ai_attribution = any(indicator in message for indicator in ai_indicators)

    if not has_ai_attribution:
        log.info("No AI attribution found in last commit message")
        return 0

    log.info("Found AI attribution in last commit message")

    # Check authorship
    check_commit_authorship()

    # Clean the message
    cleaned_message = clean_commit_message(message)

    # Get current git user
    name, email = get_git_user()
    author = f"{name} <{email}>"

    # Show what will be changed
    log.info("Original message:")
    for line in message.split("\n"):
        log.info(f"  {line}")

    log.info("Cleaned message:")
    for line in cleaned_message.split("\n"):
        log.info(f"  {line}")

    log.info(f"New author: {author}")

    # Amend the commit
    amend_commit(cleaned_message, author)

    return 0


if __name__ == "__main__":
    sys.exit(main())
