# Project:   hyperi-pylib
# File:      .github/workflows/ci.yml
# Purpose:   CI pipeline
#
# License:   BUSL-1.1
# Copyright: (c) 2026 HYPERI PTY LIMITED

name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true
        description: "Tag to publish (e.g. v2.27.1)"

permissions:
  contents: write
  issues: write
  packages: write
  pull-requests: write

jobs:
  ci:
    uses: hyperi-io/hyperi-ci/.github/workflows/python-ci.yml@main
    with:
      publish-target: oss
      tag: ${{ inputs.tag || '' }}
    secrets: inherit
