name: Release

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  build:
    name: Build
    uses: hypersec-io/ci/.github/workflows/_reusable/build.yml@main
    secrets: inherit

  publish:
    name: Publish to JFrog
    needs: build
    uses: hypersec-io/ci/.github/workflows/_reusable/publish.yml@main
    with:
      artifact-name: dist-python
    secrets: inherit
